// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zhaoxi.GameManagement.EntityFramework;

#nullable disable

namespace Zhaoxi.GameManagement.EntityFramework.Migrations
{
    [DbContext(typeof(GameManagementDbContext))]
    [Migration("20231212121301_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Zhaoxi.GameManagement.Entites.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Classes")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20b5e46a-8219-4680-b20b-9da3bee9c8dc"),
                            Classes = "Mage",
                            DateCreated = new DateTime(2023, 12, 12, 20, 13, 1, 354, DateTimeKind.Local).AddTicks(6779),
                            Level = 99,
                            Nickname = "Code Man",
                            PlayerId = new Guid("60ac4d21-2128-4121-ad9a-8600eb4f50b6")
                        },
                        new
                        {
                            Id = new Guid("98e12add-3637-4ca0-b29e-8641de0f1940"),
                            Classes = "Warrior",
                            DateCreated = new DateTime(2023, 12, 12, 20, 13, 1, 354, DateTimeKind.Local).AddTicks(6864),
                            Level = 90,
                            Nickname = "Iron Man",
                            PlayerId = new Guid("60ac4d21-2128-4121-ad9a-8600eb4f50b6")
                        },
                        new
                        {
                            Id = new Guid("c933fa97-f726-4b18-a033-4f62c004f67e"),
                            Classes = "Druid",
                            DateCreated = new DateTime(2023, 12, 12, 20, 13, 1, 354, DateTimeKind.Local).AddTicks(6866),
                            Level = 80,
                            Nickname = "Spider Man",
                            PlayerId = new Guid("60ac4d21-2128-4121-ad9a-8600eb4f50b6")
                        },
                        new
                        {
                            Id = new Guid("3753d38f-7540-4c4e-8f40-acd340cedd2e"),
                            Classes = "Death Knight",
                            DateCreated = new DateTime(2023, 12, 12, 20, 13, 1, 354, DateTimeKind.Local).AddTicks(6868),
                            Level = 90,
                            Nickname = "Batman",
                            PlayerId = new Guid("b086fdbe-af78-408a-ac13-bc769c997116")
                        },
                        new
                        {
                            Id = new Guid("c4d04597-a30f-4b0f-8ee5-a947ca14e34f"),
                            Classes = "Paladin",
                            DateCreated = new DateTime(2023, 12, 12, 20, 13, 1, 354, DateTimeKind.Local).AddTicks(6869),
                            Level = 99,
                            Nickname = "Superman",
                            PlayerId = new Guid("b086fdbe-af78-408a-ac13-bc769c997116")
                        });
                });

            modelBuilder.Entity("Zhaoxi.GameManagement.Entites.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60ac4d21-2128-4121-ad9a-8600eb4f50b6"),
                            Account = "mw2021",
                            AccountType = "Free",
                            DateCreated = new DateTime(2023, 12, 12, 20, 13, 1, 354, DateTimeKind.Local).AddTicks(6126)
                        },
                        new
                        {
                            Id = new Guid("b086fdbe-af78-408a-ac13-bc769c997116"),
                            Account = "dc2021",
                            AccountType = "Free",
                            DateCreated = new DateTime(2023, 12, 12, 20, 13, 1, 354, DateTimeKind.Local).AddTicks(6140)
                        });
                });

            modelBuilder.Entity("Zhaoxi.GameManagement.Entites.Character", b =>
                {
                    b.HasOne("Zhaoxi.GameManagement.Entites.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Zhaoxi.GameManagement.Entites.Player", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
